### ISSUE TITLE
Idea can't find Android classes when using SDK for API 21

### ISSUE THREAD

**Issue by magicgoose** [pfn/android-sdk-plugin#116]
basically, all android.* packages are inaccessible in Idea.
Although, this can be fixed by manually setting right _Module SDK_.
Initially there's "Android API 1 Platform", which is very strange.

but I can build and run my project from sbt command line just fine, so it must be an issue in `sbt-idea` plugin?

I created the project by running `gen-android android-19 <package> <name>`.
My global build.sbt is like this:

	addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.3.5")

	resolvers += Resolver.sbtPluginRepo("snapshots")

	addSbtPlugin("com.hanhuy.sbt" % "sbt-idea" % "1.7.0-SNAPSHOT")

**Comment by magicgoose** [comment]
Today, with latest IDEA, even this doesn't work…

**Comment by pfn** [comment]
It works. do not reopen issues for no reason.

**Comment by pfn** [comment]
Add an API 21 platform SDK if you want API 21.

**Comment by magicgoose** [comment]
oops. I forgot that I actually did delete that folder…
I'm sorry!
