### ISSUE TITLE
warning spam in aars task

### ISSUE THREAD

**Issue by tek** [pfn/android-sdk-plugin#135]
[This](https://github.com/pfn/android-sdk-plugin/blob/master/src/tasks.scala#L127) is being printed in each step of the build process for each aar in my deps. As I use quite a lot of subprojects in a dependency chain, this really obstructs the build output. Is the warning about a real issue that can be mitigated in my build config? Otherwise, it would be nice to silence it.

**Comment by ritschwumm** [comment]
the link seems to be broken

**Comment by tek** [comment]
damn, thanks ;)
