### ISSUE TITLE
Where can I find 1.3.14?

### ISSUE THREAD

**Issue by aginiewicz** [pfn/android-sdk-plugin#136]
Hello - on the page it says that 1.3.14 is current release, but sbt cannot find it - it says "unresolved dependency: com.hanhuy.sbt#android-sdk-plugin;1.3.14: not found" - did something, like package, changed?

**Comment by pfn** [comment]
Waiting for jsuereth to add it on bintray

--

**Comment by pfn** [comment]
fixed, it is now linked on bintray
