### ISSUE TITLE
API Level isn't warned

### ISSUE THREAD

**Issue by drhr** [pfn/android-sdk-plugin#137]
I have the project's minSdkVersion set to 14, but am using an API Level 17 function from the android SDK.  Neither SBT nor IDEA warn or throw errors about this, as would happen in a Java project.

**Comment by pfn** [comment]
this won't be supported for the forseeable future. perhaps report a similar
bug for intellij to handle at youtrack.

**Comment by pfn** [comment]
Looks like lint implemented this as a bytecode inspection, so this feature will go into 1.3.22
