### ISSUE TITLE
If ANDROID_HOME doesn't end with / then adb command cannot be found

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [pfn/android-sdk-plugin#141]
This is stack trace:

    java.lang.RuntimeException: no devices connected
        at scala.sys.package$.error(package.scala:27)
        at android.Commands$.targetDevice(commands.scala:611)
        at android.Tasks$$anonfun$101.apply(tasks.scala:1582)
        at android.Tasks$$anonfun$101.apply(tasks.scala:1579)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
 
I think this small error, can be easily corrected.

**Comment by pfn** [comment]
That error is no devices connected, not that adb can't be found.

**Comment by DavidPerezIngeniero** [comment]
Device was connected.
It is due to adb not being found.
I've changed my sdkPath definition and it now works ok:

		tsdkPah in Android := {
			val a = System.getenv("ANDROID_HOME")
			if (a == null || !file(a).isDirectory) {
				println("No encontrada variable de entorno ANDROID_HOME ")
				"/home/d/bin/android-sdks/"
			} else if (a.endsWith("/") || a.endsWith("\\"))
				a
			else
			    // Asegurarse de que termine en "/", pues en caso contrario no localiza a ADB.
				a + "/"

**Comment by pfn** [comment]
I do not experience this issue on OSX or Linux nor Windows.

There must be another problem at play now.

**Comment by pfn** [comment]
What is the output of `adb devices` and `sbt devices` from sbt when this occurs?

**Comment by DavidPerezIngeniero** [comment]
I'm using Linux.

$ adb devices
List of devices attached 
4203c9eddca37100        device

$ sbt devices
[info] Loading project definition from /home/d/des/android/project
[info] Set current project to raiz (in build file:/home/d/des/android/)
[info] Connected devices:
[info]   4203c9eddca37100       young2nfc3g

If you don't see an easy solution, then I would close this issue, as it isn't a very important problem.

**Comment by pfn** [comment]
I don't see a problem... Both commands give the same result, so
ANDROID_HOME is not the problem

--
