### ISSUE TITLE
Importing in IntelliJ 14 fails because of support-v4

### ISSUE THREAD

**Issue by alcarvalho** [pfn/android-sdk-plugin#142]
I don't really know if this is the right place to report this or if this is totally IntelliJ's Scala plugin's fault.

That being said, when I try to import the project in IntelliJ 14 I get the following error:

```
[warn] 	[FAILED     ] com.android.support#support-v4;21.0.3!support-v4.jar:  (0ms)
[warn] ==== local: tried
[warn]   /Users/xxx/.ivy2/local/com.android.support/support-v4/21.0.3/jars/support-v4.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
[warn] ==== google libraries: tried
[warn]   file:/Users/xxx/src/android/android-sdk/extras/google/m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
[warn] ==== android libraries: tried
[warn]   file:/Users/xxx/src/android/android-sdk/extras/android/m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.android.support#support-v4;21.0.3!support-v4.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

I have the following dependencies that could be the culprits:

```scala
libraryDependencies ++= Seq(
  aar("com.android.support" % "support-v4" % "21.0.3" intransitive()),
  aar("com.android.support" % "appcompat-v7" % "21.0.3" intransitive()),
  "com.google.android.gms" % "play-services" % "6.+" intransitive(),
...
```

As you may notice, I have manually added the support-v4 as an aar and tried to make all of them intransitive, but this doesn't solve the problem.

**Comment by pfn** [comment]
Ignore the error, import did not fail. It is just looking for jar in
addition to aar

--

**Comment by alcarvalho** [comment]
This was fast! Thank you!!!

Oh my! And I have been using gen-idea and manually compiling the project from sbt console so that IntelliJ will autocomplete my code correctly all this time... :sob: 

All I had to do was to delete the generated project files and importing it, ignoring this error.
Thanks again!
