### ISSUE TITLE
Local libs/*.jar files are not included in published aar

### ISSUE THREAD

**Issue by Taig** [pfn/android-sdk-plugin#143]
I have an android-sdk-plugin aar project that relies on `libs/androidsvg-1.2.2-beta-1.jar`, `src/main/libs/androidsvg-1.2.2-beta-1.jar` (tried both). Compile and publish works fine, however when I depend on the aar project from an app that runs proguard it will warn me about missing classes `can't find referenced class com.caverock.androidsvg.SVG`.

Manually adding the jar file to the app works of course, but is there a way to bundle the jar from the libs folder with the aar project?

**Comment by Taig** [comment]
I just realized that the project is also available on mavencentral. Referencing it as library dependency ` "com.caverock" % "androidsvg" % "1.2.2-beta-1"` resolves my issue.

**Comment by pfn** [comment]
currently, the best approach is to manually add to the aar, e.g. and fix as appropriate for syntax, etc
```
packageAar in Android ~= { aar =>
  // unfortunately, no java apis exist for updating an existing jar, fork the command instead
  Process(Seq("jar", "uf", aar.getAbsolutePath, "libs/foobarbaz.jar"),
   baseDirectory.value / "src" / "main" /* omit src/main if necessary */)) !

  aar
}
```

including unmanaged libraries into an aar that gets published is highly discouraged. especially if it's a 3rd party dependency.
