### ISSUE TITLE
(on xxxhdpi device) xxxhdpi resources aren't used when there are alternatives with lower density

### ISSUE THREAD

**Issue by magicgoose** [pfn/android-sdk-plugin#146]
the same layout but done in Android Studio doesn't invoke this issue.
more details here: http://stackoverflow.com/q/28607550/1418097
(APK file: http://dropbox.com/s/lqdj9w7iimh2gj9/magicgoose-example-debug.apk?dl=0
Source code: http://dropbox.com/s/cs4pngpkvkoe5q2/dpi-example-src.zip?dl=0)

I don't understand how the SBT & this plugin can cause this, but… it does happen. Maybe the plugin does something special to the resources?

**Comment by pfn** [comment]
What drawable is having the problem in particular.

**Comment by pfn** [comment]
This looks immediately wrong:

```
$ aapt d badging magicgoose-example-debug.apk
package: name='magicgoose.example' versionCode='1' versionName='1.0' platformBuildVersionName='5.0.1-1624448'
sdkVersion:'10'
targetSdkVersion:'1'
```

targetSdkVersion should be at least 19 or higher if you want xxxhdpi

**Comment by magicgoose** [comment]
> What drawable is having the problem in particular.

There's only one, except launcher icon.

> This looks immediately wrong:

Hmmm, I don't know how it got there… let me check…

**Comment by pfn** [comment]
You set min sdk in sbt, don't, set it in manifest

--

**Comment by magicgoose** [comment]
Looks like the problem is gone if I **also** change minimum SDK to 14. Okay… let me experiment for some time. Thank you for help!

**Comment by magicgoose** [comment]
by the way, it's strange that target SDK is not set to latest by default… (my two cents)

**Comment by pfn** [comment]
What does latest mean, it's independent of the plugin, don't set the wrong
values, or even not at all.

--
