### ISSUE TITLE
Too much output with retrolambda

### ISSUE THREAD

**Issue by seroperson** [pfn/android-sdk-plugin#148]
When I use retrolambda it print all *.class files in "included files: ..." (is about 2k lines for me) and I did not find any option to disable it (except that disable retrolabda). 
P.S. Maybe there is some temporary hack to suppress this output until it is not fixed?

**Comment by pfn** [comment]
Is the output coming from retrolambda or from the plugin? If the former, a request to retrolambda should be made to squelch this output.

**Comment by seroperson** [comment]
I think that it comes from plugin because I ran retrolambda standalone on some file and there is no "included files: *filelist*"

**Comment by pfn** [comment]
There is no such message in the plugin.

**Comment by seroperson** [comment]
I don't know what exactly produces this output but after upgrading to 1.3.17 it came away.
