### ISSUE TITLE
How to set versionName and versionCode in sbt? 

### ISSUE THREAD

**Issue by erawhctim** [pfn/android-sdk-plugin#150]
How do I set these values in `build.sbt`? 

I tried setting them like this: 
```
versionCode in Android := Some(123)
versionName in Android := Some("1.1")
```

but the resulting APK file doesn't reflect the changes. Additionally, when building a release version, SBT throws an error `Manifest merger failed : Attribute manifest@versionName at AndroidManifest.xml:2:1 requires a placeholder substitution but no value for <versionMajor> is provided`

Is there a way to dynamically set `versionName` and `versionCode` in the SBT build file, rather than declaring them in `AndroidManifest.xml`?

**Comment by pfn** [comment]
What you have should work fine. Sounds like you have manifest placeholders set but aren't filling in the placeholders instead.

**Comment by pfn** [comment]
A test case I have just tried indicates that it works fine.

**Comment by pfn** [comment]
steps:

`sbt 'gen-android android-21 com.example Foo'`
`echo sbt.version=0.13.5 > project/build.properties`
`echo 'versionName in Android := Some("1.2.3")\n\nversionCode in Android := Some(1234)' > build.sbt`
`sbt android:package-debug android:package-release`
`$ANDROID_HOME/build-tools/VERSION/aapt d badging target/android-bin/com-example-{debug,release-unsigned}.apk`

**Comment by erawhctim** [comment]
Thanks for the clarification. Seems like running that example code (`sbt 'gen-android android-21 com.example Foo'`) you gave throws an error about `ANDROID_HOME` not being set properly (error is `RuntimeException: ANDROID_HOME or sdk.dir is not set`).... even though `echo $ANDROID_HOME` returns the proper result... I just installed the android-sdk-plugin globally and ran that first line. Any ideas?

**Comment by pfn** [comment]
export your environment variables.

--

**Comment by erawhctim** [comment]
They are already globally available... I use them in various other places without issue

**Comment by pfn** [comment]
Doesn't sound like it's available going by the error you get

--

**Comment by erawhctim** [comment]
Okay so I have a new issue here... I can't get the test project command above to work, but I adapted what I am trying to do with my existing project and build file.

I am trying to create 4 variables, `versionMajor`, `versionMinor`, `versionPatch`, and `versionBuild` and dynamically combine them to form the `versionCode` and `versionName` properties. 

I have this so far:
```
...

platformTarget in Android := "android-21"

buildToolsVersion in Android := Some("21.1.1")

val versionMajor = 1
val versionMinor = 0
val versionPatch = 0
val versionBuild = 2

manifestPlaceholders in Android := Map(
    "versionMajor" -> "${versionMajor}",
    "versionMinor" -> "${versionMinor}",
    "versionPatch" -> "${versionPatch}",
    "versionBuild" -> "${versionBuild}"
)

versionCode in Android := Some(versionMajor*10000 + versionMinor*1000 + versionPatch*100 + versionBuild)

versionName in Android := Some("${versionMajor}.${versionMinor}.${versionPatch}.${versionBuild}")

...
```

Everything seems to be working, however the actual string value for `versionName` in the final APK comes out to be `"${versionMajor}.${versionMinor}.${versionPatch}.${versionBuild}"` explicitly, instead of evaluating and replacing the variables. I expect the `versionName` to equal `"1.0.0.2"`. How can I fix that?

**Comment by pfn** [comment]
1. You're mixing manifest placeholders and version code/name in sbt, that is absolutely the incorrect thing to be doing, use one or the other. 

2. You're also trying to interpolate strings without using the correct interpolation format. 

Solution, remove manifest placeholders, prefix your version name with `s`, e.g

`versionName in Android := Some(s"${versionMajor}")`

**Comment by erawhctim** [comment]
Ah, I see now. I guess since the string interpolating was wrong, the manifest merging was expecting those variables as placeholders. Looks like it is working now. Thank you for the help!

**Comment by pfn** [comment]
manifest placeholders are only for the XML file.
