### ISSUE TITLE
Aar package task doesn't lower case the project name

### ISSUE THREAD

**Issue by Taig** [pfn/android-sdk-plugin#151]
````scala
Project( "some-id", file( "." ), settings = androidBuildAar )
    .settings(
        organization := "org.test",
        name := "PROJECT-NAME"
    )
````

````
> publishLocal
....
[info] Packaging PROJECT-NAME.aar
[info] Done packaging.
[info] 	published project-name_2.11 to ~/.ivy2/local/org.test/project-name_2.11/1.0.0/poms/project-name_2.11.pom
[info] 	published project-name_2.11 to ~/.ivy2/local/org.test/project-name_2.11/1.0.0/srcs/project-name_2.11-sources.jar
[info] 	published project-name_2.11 to ~/.ivy2/local/org.test/project-name_2.11/1.0.0/docs/project-name_2.11-javadoc.jar
[info] 	published PROJECT-NAME_2.11 to ~/.ivy2/local/org.test/project-name_2.11/1.0.0/aars/PROJECT-NAME_2.11.aar
[info] 	published ivy to ~/.ivy2/local/org.test/project-name_2.11/1.0.0/ivys/ivy.xml
````

Which will then make the dependency unresolvable via `"org.test" %% "project-name" % "1.0.0"`, because project-name.aar can not be found!

**Comment by pfn** [comment]
Project name is case sensitive. It is not unresolvable, you are searching
for the wrong name

--

**Comment by Taig** [comment]
Here is a project that is affected by this issue:
http://search.maven.org/#artifactdetails%7Cio.taig.android%7Cparcelable_2.11%7C1.2.4%7Caar

Using the provided sbt dependency code `libraryDependencies += "io.taig.android" % "parcelable_2.11" % "1.2.4"` results in the following error:

````
[warn] 	[FAILED     ] io.taig.android#parcelable_2.11;1.2.4!parcelable_2.11.aar:  (0ms)
[warn] ==== local: tried
[warn]   /Users/Taig/.ivy2/local/io.taig.android/parcelable_2.11/1.2.4/aars/parcelable_2.11.aar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/taig/android/parcelable_2.11/1.2.4/parcelable_2.11-1.2.4.aar
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.taig.android#parcelable_2.11;1.2.4!parcelable_2.11.aar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: download failed: io.taig.android#parcelable_2.11;1.2.4!parcelable_2.11.aar
[error] Total time: 1 s, completed 11.03.2015 16:10:44
````

Works fine with 1.2.5 however, as I lowercased the project name.

**Comment by pfn** [comment]
1.2.4 is published as Parcelable, the correct incantation would be:
"io.taig.android"
%% "Parcelable" % "1.2.4"

**Comment by pfn** [comment]
Provide a maven/nexus specification that indicates artifacts should be
lower-cased if the name is upper case, then I will consider implementing
this. Until then, this issue is closed.

**Comment by Taig** [comment]
That's the problem here. `"io.taig.android" %% "Parcelable" % "1.2.4"` does not solve this! Because now the other files (e.g. https://repo1.maven.org/maven2/io/taig/android/Parcelable_2.11/1.2.4/Parcelable_2.11-1.2.4.pom) can not be resolved anymore.

The aar task creates an upper case file while the pom, javadoc and sources are lowercase. This way it is impossible to resolve the dependency because it will either fail with the missing *.aar or with the *.pom.

**Comment by pfn** [comment]
the correct answer seems to be that you should name your project lowercase, as this is autogenerated by sbt

**Comment by Taig** [comment]
That's what I'm doing. I just wanted to let you know about this as a possible enhancement. For me this was unexpected behavior as it works in other sbt based projects and I generally like to upper case names as linguistic convention.

**Comment by pfn** [comment]
I would argue that this is a bug in sbt, if it is a bug; do ivy repos suffer from the same problem of mismatched case?

**Comment by Taig** [comment]
I just had another look at the sbt doc and found a few words about this topic which you can find here:

http://www.scala-sbt.org/0.13/docs/Howto-Project-Metadata.html#Set+the+project+name

I didn't come across the sbt key `normalizedName` until now, but this seems to be what this plugin should be using for the aar's name.

````
Project( "id", file( "." ), settings = androidBuildAar )
    .settings(
        organization := "org.test",
        name := "name",
        normalizedName := "normalized-name"
    )
````

````
> publishLocal
....
[info] Packaging name.aar
[info] Done packaging.
[info]  published normalized-name_2.11 to ~/.ivy2/local/org.test/normalized-name_2.11/1.0.0/poms/normalized-name_2.11.pom
...
[info]  published name_2.11 to ~/.ivy2/local/org.test/normalized-name_2.11/1.0.0/aars/name_2.11.aar
````

**Comment by Taig** [comment]
Thank you :+1:
