### ISSUE TITLE
proguardScala setting issues

### ISSUE THREAD

**Issue by wpc009** [pfn/android-sdk-plugin#153]
I find that the "useProguard" and "useProguardInDebug" settings are using the value of "proguardScala".
That's a little confusing, since the description of "proguardScala" setting is "include scala-library in proguard: true if scala source present". 
I think it means `if "proguardScala" is true, then we include scald-library in proguard. else not.`
But setting "proguardScala" to false cause "useProguard" and "useProguardInDebug" to false. 
The question is I only want to exclude scald-library from proguard by setting "proguardScala" to false. But instead I disable proguard unexpected.

So. It will be nice to update the description or  not using the proguardScala's value on "useProguard" and "useProguardInDebug" setting keys.

**Comment by pfn** [comment]
If you're using scala, you must not set proguardScala to false, and the
default is to use proguard only if proguardScala is true

--

**Comment by pfn** [comment]
To be clear: proguard is disabled by default unless you are working with
scala.

--

**Comment by wpc009** [comment]
I know that. 

Preinstall scala to android system is another option. We do not need proguard scala library for every projects. So, disable "proguardScala" is needed.

I'm complain the setting doesn't works like it said in the description.

**Comment by pfn** [comment]
But it does work like in the description. If you do not individually enable
proguard, then why would proguard run?

--

**Comment by pfn** [comment]
Also, pre-installed scala on device is not a supported nor tested
configuration.

--
