### ISSUE TITLE
Adding an android test dependency?

### ISSUE THREAD

**Issue by sgrif** [pfn/android-sdk-plugin#155]
A library dependency added such as:

```
  "com.android.support.test.espresso" % "espresso-core" % "2.0" % "test"
```

is no longer included when running `android:test`. How does one include a library dependency for instrumentation tests?

**Comment by pfn** [comment]
That has always been the case, if `android:debugIncludesTests := true` then `test` configuration dependencies were never included.

**Comment by sgrif** [comment]
So there's no way to declare a dependency which is used for instrumentation tests, but not in debug or release builds? (The equivalent of an `androidTestCompile` dependency in gradle)

**Comment by pfn** [comment]
only if you `android:debugIncludesTests := false`

**Comment by pfn** [comment]
which does not play nicely with scala

**Comment by sgrif** [comment]
Even with that setting, test dependencies are not included when compiling instrumentation tests.

**Comment by pfn** [comment]
Can you try building 1.3.19-SNAPSHOT locally and seeing if this fixes your problem?

**Comment by sgrif** [comment]
I'll see if I can this weekend. I've switched my project over to https://github.com/saturday06/gradle-android-scala-plugin already, since I've had a lot of problems with SBT and this plugin on the last several projects that I've used it on.

**Comment by pfn** [comment]
Problems with this plugin? Please elaborate. I have used this plugin on
hundreds of projects without problems. But if you're leaving, I guess I
can't make you stay.

**Comment by sgrif** [comment]
I've opened issues for most of them as I've encountered them, but to roughly sum it up:

- Poor multidex support
- Very poor support for actually being able to test your apps (if you run `sbt clean android:test` on any of your test builds which have instrumentation tests, they won't even compile)
- Difficult to build or compose upon because everything is structured around tasks when they should be a separate project (for example in this particular issue, if you've made it so `% "test"` specifies a dependency for instrumentation tests, how do I specify a dependency for normal JVM unit tests? Both of these should be separate projects that I can reference as an object in my build file for things like this)

**Comment by pfn** [comment]
* Multidex is fully supported
* Testing is fully supported, works fine for me?
* "test" dependencies are specified for both jvm and instrumentation tests, unless you use debugIncludesTests.

**Comment by sgrif** [comment]
- Multidex is incredibly slow compared to where the gradle toolchain is at right now
- Multidex with this tool is incredibly buggy (the reason I switched tools yesterday was when doing nothing other than adding Macroid to my dependencies caused my test classes to stop being detected by the instrumentation runner. I'll isolate and open an issue for you this weekend)

> Testing is fully supported, works fine for me?

No offense, but glancing through your github profile (which you claim in the README is the best source of information about how to use this tool), you have no apps with tests.

> "test" dependencies are specified for both jvm and instrumentation tests, unless you use debugIncludesTests.

Which as I've repeatedly stated in this issue, and in others, is not sufficient. Dependencies that you would use in isolated JVM tests often conflict with dependencies that you'd use for instrumentation tests, or even with Android itself. Which is why every other tool out there separates out:

- compile time dependencies
- runtime dependencies
- unit test compile time dependencies
- unit test runtime dependencies
- instrumentation test compile time dependencies
- instrumentation test runtime dependencies

**Comment by pfn** [comment]
multidex and scala are slow in general. if you have a suggestion to make it
faster, do so.

In any case, testing works fine, if it doesn't work for you, then I'm
sorry. That's all I can offer.
