### ISSUE TITLE
Consider creating a g8 template

### ISSUE THREAD

**Issue by darkfrog26** [pfn/android-sdk-plugin#160]
It would be very beneficial to have a g8 template to quickly set up a project using this plugin.

**Comment by pfn** [comment]
no, use gen-android.

**Comment by darkfrog26** [comment]
Okay, I was able to run that, but when I try to package it I get:
'''
(android:apkbuild) java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/JcaJceHelper
'''

**Comment by pfn** [comment]
You have an incompatible version of bouncycastle loaded into your build environment, probably caused by something out of date like sbt-pgp

**Comment by darkfrog26** [comment]
Ah, I see. I'm running the latest version of sbt-pgp though (1.0.0).  How do I override the dependency?

**Comment by pfn** [comment]
Unfortunately, I don't believe there is a way to resolve the conflict, but
you can downgrade sbt-pgp to 0.8.1 which I use currently and works.
Hopefully google will update their libraries at some point in the future to
compatible versions.

**Comment by darkfrog26** [comment]
That did the trick, thanks. :)
BTW, I would recommend updating the documentation to specify that gen-android requires arguments.

**Comment by dejvid** [comment]
Hi, 
 how you did downgrade sbt-pgp to 0.8.1.  Can you explain please.
Im new to this plugin and Im experiecing this error after android-gen, Using android-sdk-plugin 1.4.9, scala 2.11.6. 

```
[error] (Android/android:apkbuild) java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/JcaJceHelper
```

**Comment by pfn** [comment]
addSbtPlugin("..." % "sbt-pgp" % "0.8.1") in the correct place with the
correct organization name.

**Comment by dejvid** [comment]
Thank you. Ok i feel stupid now. I thought sbt-pgp was dependent on some other plugin. I dont have sbt-pgp plugin in my current build project. But that gave me initiative to find the guilty one: 
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")
```
I realy need this plugin, i cant just change version to some older one. Is there any other way to include correct bouncycastle library? Some explicit override libraryDependency ?

**Comment by dejvid** [comment]
Well I could just make separate  build.sbt and not including  `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")`  plugin. But that will break beauty of current multi project setup. Is there any other way?

**Comment by pfn** [comment]
There is no other way, android build libraries depend on the older versions
of bouncycastle.
