### ISSUE TITLE
Resource prefix for lib project as the android gradle plugin

### ISSUE THREAD

**Issue by vmlinz** [pfn/android-sdk-plugin#166]
I am creating an aar, but I am afraid of resource conflict with the app, so would it possible to do a resource prefix like android gradle plugin?

In android gradle, when producing aar libs, we can add an option `resourcePrefix 'prefix_'` to add prefix to resources, so that it is hard to conflict with app resources.

Br,

**Comment by pfn** [comment]
Pretty low priority on this for me, if someone wants to point at how this
is implemented in gradle and possibly make a pull request, I would
appreciate it.

--

**Comment by vmlinz** [comment]
Thanks for the reply, I'll look into the gradle plugin and try to make it if possible.

**Comment by Taig** [comment]
I hate the Android SDK for its crippled xml namespacing. Prefixing is ugly but the only reasonable way around the SDK flaws. I didn't know that Gradle provided such a feature. Would love to see this here as well. It's obviously not super urgent, one can just hardcode the prefixes for now.

+1

**Comment by pfn** [comment]
So, I looked into this, it appears to be for creating new resources from Android Studio only. It does not translate existing names into this prefix. As such, I will likely not implement anything like this.

**Comment by pfn** [comment]
For reference https://android.googlesource.com/platform/tools/base/+/master/build-system/gradle/src/main/groovy/com/android/build/gradle/BaseExtension.groovy#130
