### ISSUE TITLE
Macro paradise compiler plugin not working for macro annotations

### ISSUE THREAD

**Issue by zainab-ali** [pfn/android-sdk-plugin#169]
The macro paradise plugin isn't working for type provider example http://docs.scala-lang.org/overviews/macros/typeproviders.html. The annotation doesn't get expanded at compile time and we get the annotation error. 

The setup of the project is using the androidBuild with macro, core and a root project which depends on both the former.

**Comment by pfn** [comment]
upload a sample project where this fails.

you need to add the macro paradise compiler plugin if you want to use macro
paradise macros

**Comment by zainab-ali** [comment]
Here is a sample project https://github.com/yilinwei/coffee-madeleine.

**Comment by pfn** [comment]
make a project that has barely what is necessary to reproduce this issue, I'm not going to publish any local artifacts to test this. (e.g. macroid 2.0.0-M4)

**Comment by yilinwei** [comment]
This issue can be closed, the method has to be called macroTransform for macro annotations. Not sure if this is intended.
