### ISSUE TITLE
Unit testing support with mockable android

### ISSUE THREAD

**Issue by fedefernandez** [pfn/android-sdk-plugin#171]
Hi,

I'm wondering if is possible to bring support to unit testing with mockable version on android. [From version 1.1 of android gradle plugin, you can run unit tests against a mockable version of android.jar where all final modifiers have been stripped off. This lets you use popular mocking libraries, like Mockito](http://tools.android.com/tech-docs/unit-testing-support).

The mechanism seems to be not very complex, there are a task that creates the mockeable version of android jar and add it to the classpath. 

I'm not very familiar with the code of this plugin, but I've found how this is made in the gradle side:

* [Method task](https://android.googlesource.com/platform/tools/base/+/ce3e60ce7666e278eaf8638be142531938c9b76b/build-system/gradle/src/main/groovy/com/android/build/gradle/internal/TaskManager.groovy#251)
* [MockableAndroidJarTask](https://android.googlesource.com/platform/tools/base/+/ce3e60ce7666e278eaf8638be142531938c9b76b/build-system/gradle/src/main/groovy/com/android/build/gradle/internal/tasks/MockableAndroidJarTask.groovy)
* [MockableJarGenerator](https://android.googlesource.com/platform/tools/base/+/ce3e60ce7666e278eaf8638be142531938c9b76b/build-system/builder/src/main/java/com/android/builder/testing/MockableJarGenerator.java)

**Comment by pfn** [comment]
Thanks for looking into and digging for the underlying implementation.

However, this is pretty low on the priority stack for me, so if anyone would like to make a PR out of the details, I'd appreciate it.

**Comment by pfn** [comment]
Actually, MockableJarGenerator is already included as a dependency by android-sdk-plugin.

You should be able to do something like:

```
val generateMockableJar = taskKey[File]

generateMockableJar := {
  val out = baseDirectory.value / Wherever / You / Want / "MockableAndroid.jar"
  val androidJar = (bootClasspath in Android).value collect {
    case x if x.data.getName == "android.jar" => x.data
  } head

  val generator = new com.android.builder.testing.MockableJarGenerator(true)
  generator.createMockableJar(androidJar, out)
  out
}
```

How you load this into mockito or whatever is an exercise I'll leave for you to implement.

**Comment by pfn** [comment]
If there's a pull request that can accommodate the above, I would consider adding it. But as-is, the snippet above should enable testing with a mockable android.jar.

**Comment by fedefernandez** [comment]
Great @pfn! This should work! Thanks
