### ISSUE TITLE
support for unmanagedClasspath in Runtime ?

### ISSUE THREAD

**Issue by oranda** [pfn/android-sdk-plugin#174]
This used to work with the Berkel plugin:

unmanagedClasspath in Runtime <+= (baseDirectory) map { bd => Attributed.blank(bd / "config") }

The config directory could be accessed by unmanaged dependencies as well as the current project.

I can't get it to work with android-sdk-plugin 1.3.24. What's the new way of doing things? It would help if there were a sample project with an application.conf.

**Comment by pfn** [comment]
src/main/resources or resources/

--

**Comment by oranda** [comment]
Adding application.conf to src/main/resources solves the essential problem.
