### ISSUE TITLE
1.4.0 key conflict with sbt-native-plugin

### ISSUE THREAD

**Issue by guersam** [pfn/android-sdk-plugin#178]
I have a build.sbt with multiple subprojects such as some servers, desktop client and android client, some of them are packaged by sbt-native-plugin.

When I try to upgrade to android-sdk-plugin 1.4.0, sbt complains about `packageName` which are defined with the same name but different types, due to conflict with sbt-native-plugin. If it cannot be rolled back to `Setting`(I agree on change to `Task` due to it's side effect), would you consider namespacing it?

**Comment by pfn** [comment]
Any change I would make in this regard is pretty far off. My only recommendation at the moment would be to stay on a 1.3 version.
