### ISSUE TITLE
Should I explicitly enable signing? Settings in local.properties don't work

### ISSUE THREAD

**Issue by utgarda** [pfn/android-sdk-plugin#179]
Hi, and thanks for the great tool!

Following README.md, I put the following settings to local.properties, the same properties I use for manual signing with jarsigner:
```
key.alias: my-key-alias
key.store: ~/.android/release.keystore
key.store.password: my-keystore-pasword
```
but still when I run package-release I get this: 
```
$ sbt android/android:package-release
...
[warn] Package needs signing: android-release-unsigned.apk
[warn] Package needs signing and zipaligning: android-release-unsigned.apk
[success] Total time: 6 s, completed 25-Jun-2015 17:07:18
```

How should I enable signing?

**Comment by pfn** [comment]
local.properties is in the wrong place, it must be in the baseDirectory of
'android'

**Comment by utgarda** [comment]
It works, and also zipaligns the jar after signing. Thanks a bunch!

**Comment by utgarda** [comment]
Please review the new wiki page https://github.com/pfn/android-sdk-plugin/wiki/Signing-configuration
and list in in wiki home page if it's ok.

**Comment by pligor** [comment]
Our thumbs up to your contribution!

**Comment by pfn** [comment]
I would like the various [prompt signing configs](../tree/master/src/signing.scala) to be mentioned as well

**Comment by utgarda** [comment]
Cool, will do

**Comment by utgarda** [comment]
Done: https://github.com/pfn/android-sdk-plugin/wiki/Signing-configuration

Btw, would be much easier to put a line into `signing.properties` to switch between signing configs, something like `key.store.password.prompt: true` instead of actually configuring it as described. I can try to implement this.
