### ISSUE TITLE
PromptPasswordsSigningConfig doesn't work with empty/absent key password

### ISSUE THREAD

**Issue by utgarda** [pfn/android-sdk-plugin#181]
Tried to use `PromptPasswordsSigningConfig`, I've set a password only for the keystore, but not for the key. Here's what happens:

```ShellSession
$ sbt android/android:package-release
...
Enter keystore password: *** I type my password here ***
Enter password for key 'my-key': *** I just hit 'Enter' ***
jarsigner: key associated with my-key not a private key
java.lang.RuntimeException: Error signing jar (exit code was 1.)
...
[error] (android/android:signRelease) Error signing jar (exit code was 1.)
[error] Total time: 30 s, completed 27-Jun-2015 19:27:49
```

Using `PromptStorepassSigningConfig` in this case works ok.

**Comment by pfn** [comment]
The default key password is the same as the store password. If requesting
both be prompted, both must be entered, even if identical.

--

**Comment by utgarda** [comment]
All right, totally forgot this. Cause I've read it only once, though not so long ago.

**Comment by utgarda** [comment]
Maybe it could warn/notify the user about this, cause it's totally not obvious.
