### ISSUE TITLE
How to turn on mutiDex

### ISSUE THREAD

**Issue by spidfire** [pfn/android-sdk-plugin#183]
Hi, Maybe am I stupid but I seem not able to find most of the documentation for things like, mutiDex (optimizations)  and how you can use robolectric and probably 1000 other functionalities I totally know nothing about :frowning: 

Is there somewhere a secret documentation or is it "still in progress"

**Comment by pfn** [comment]
The source and test cases are the documentation.

Multidex optimization is automatically turned on if minSdkVersion is set to
21 or higher

--

**Comment by veegee** [comment]
> The source and test cases are the documentation.

Are you serious...

**Comment by pfn** [comment]
Yes, feel free to write documentation and submit a pull request. Thanks.
