### ISSUE TITLE
Unused import into TR.scala

### ISSUE THREAD

**Issue by emstlk** [pfn/android-sdk-plugin#185]
Under scala 2.11.7 with compiler option "-Ywarn-unused-import" I have got error: Unused import in TR.scala:3
Because "import scala.language.implicitConversions" is not needed to implicit vals or implicit class

**Comment by pfn** [comment]
If you can verify that this is also true in 2.10.* then I will consider removing the import.

**Comment by emstlk** [comment]
It is PR to #186

**Comment by emstlk** [comment]
I checked it also on scala 2.10.5
