### ISSUE TITLE
Feature Request: Customizable source sets per build type, build flavor

### ISSUE THREAD

**Issue by erawhctim** [pfn/android-sdk-plugin#191]
It would be great to be able to customize which source folders to be included/excluded automatically, per build type (`debug` or `release`), similar to [this](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Product-flavors)

E.g. code in `src/debug` would be included in the classpath for `debug` builds only, `src/release` for `release` builds only, and `src/main` for shared code that would be included always. 

Is this possible? Is it possible to add support for build flavors as well? I am trying to emulate the functionality of the gradle android plugin, and am not sure what is/isn't possible with SBT.

**Comment by pfn** [comment]
Flavors are already supported. Custom sources for a debug/release build is not. 

You can try modifying `sources in Compile` depending on the value of `apkbuildDebug in Android`

**Comment by erawhctim** [comment]
How can build flavors be specified?

**Comment by pfn** [comment]
https://github.com/pfn/android-sdk-plugin#new-features-in-13x-last-version-1324
