### ISSUE TITLE
If there are no sources within the /src/main/scala directory, artifact is incorrectly published

### ISSUE THREAD

**Issue by mseddon** [pfn/android-sdk-plugin#192]
As demonstrated here [https://github.com/mseddon/android-sdk-mangle].

The project is structured ala gradle correctly, except there are no sources in `/src/main/scala`, they all reside in `/others/`, listed in `unmanagedSourceDirectories` (although the same issue occurs with `sourceGenerators`).

Doing an `sbt publishLocal` in this case generates the artifact:

```[info] :: delivering :: delete-me#mangled;1.0 :: 1.0 :: release :: Sat Aug 01 15:43:31 BST 2015```

Moving the source from `others` back into `/src/main/scala` results in the correct behaviour:

```[info] :: delivering :: delete-me#mangled_2.11;1.0 :: 1.0 :: release :: Sat Aug 01 15:44:00 BST 2015```

It appears to happen whenever there are no sources in the main scala directory, despite the fact the generated aar is identical.

**Comment by pfn** [comment]
It is disabled automatically as a convenience, and this should only occur in Android projects, which typically do not get published. 

If it is in an unconventional location, then you must manually set `crossPaths := true`

**Comment by mseddon** [comment]
:+1: brilliant. Thanks!

**Comment by pfn** [comment]
Alternatively, you could update the value of `scalaSource in Compile`

**Comment by mseddon** [comment]
Yep- that did the trick. I might try with `scalaSource`, also.  Definitely worth a mention in the readme.md I think.  Thanks for your help, sanity is restored :)
