### ISSUE TITLE
apk gets bloated after second android:package

### ISSUE THREAD

**Issue by kirillkh** [pfn/android-sdk-plugin#194]
When I run android:clean, followed by android:package on the sample project referenced below, it outputs a nice little 311Kb apk with 5907 methods. When I rerun android:package without changing anything, it creates an apk twice the size and with 3 times the method count. After that the bloating stops, i.e. it doesn't grow again if I keep executing android:package.

https://github.com/kirillkh/macroid_sample_project

**Comment by pfn** [comment]
That is the nature of proguard cache.

cache hit = no proguard = more methods.

**Comment by kirillkh** [comment]
I would like to understand how this works. So my current theory is as follows. From ProGuard's viewpoint, the application is split into two parts: A=library, B=user code.
  - When performing a clean build, the plugin first runs ProGuard on (A + B), the code that remains from A is saved as A' and the code that remains from B is saved as B'. The plugin also saves all entry points (classes and functions) by which B accesses A' as S. Then it outputs A'+B' as the resulting bytecode.
- When a saved A' exists, the plugin makes a fresh set of entry points in A used by B. If the set is a subset of S, then the plugin calls it a cache hit and outputs A' + B as the resulting bytecode. Otherwise the plugin computes new A' and B' and outputs A'+B' as the resulting bytecode.

Is this a close enough description of what's going on? Assuming it is, then, as a user, I am interested to include as much libraries that I use into part A and make part B as light as possible. How do I achieve that?

**Comment by pfn** [comment]
Close  enough, but you shouldn't care unless it has a material impact on build and/or deploy times.

Release builds do not use proguard cache.

If you insist, you can add more packages to `proguardCache in Android` but it means proguard will run more often.

**Comment by kirillkh** [comment]
I'm tried to add 
  proguardCache in Android ++= Seq("org.scaloid", "org.macroid", "com.android.support", "scala.tools.nsc")

But it doesn't have any effect.

**Comment by pfn** [comment]
The package name for support is `android.support`, likewise for macroid, it is `macroid`, not `org.macroid`

everything in `scala` is cached by default (why are you making use of scala.tools.nsc anyway).

**Comment by pfn** [comment]
Once again, in development, the dex size doesn't matter unless it has an impact on  your build/deploy times.

**Comment by kirillkh** [comment]
Thanks, that worked. scala.tools.nsc was there by mistake. You are right it doesn't make much difference (6 vs 5 seconds on cache hit), I just wanted to do this to be sure that it's doable for the future. How do you know that the package name should be just "macroid" "scaloid" and not org.*? Is the first domain name always dropped?

**Comment by pfn** [comment]
The package name in code, not the organization of the module.
