### ISSUE TITLE
Install instructions and Usage error

### ISSUE THREAD

**Issue by accesio** [pfn/android-sdk-plugin#195]
Hi,

Considering that SBT is a newer tool on the software build scene, it would be useful to include more helpful instructions on how to get your module installed.

For instance, I created the file 
~/.sbt/0.13/plugins/android.sbt  that has the sole line
```shell
lineaddSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.3.18")
```

But then what do I do after that ?  How do I verify that SBT knows about this plugin ?  How about a line saying

```bash
sbt plugins | grep AndroidPlugin 
```

Also, you might want to mention that sbt doesn't show plugins correctly if you are inside of a project ( which to me is terrible ) 

Second issue;  Your second line of instructions just has "Create a new android project using _gen-android_"  .  

Can you change the documentation to say  , now run

```bash
sbt gen-android 18 com.FooBar FooBar
```

but this fails too in non-intuitive way saying just: 

[info] Loading global plugins from /home/jdamon/.sbt/0.13/plugins
[info] Set current project to androidscala (in build file:/media/jdamon/Development/Documents/Projects/learning_scala/AndroidScala/)
[error] Usage: gen-android <platform-target> <package-name> <name>

I have yet to get passed this error

Lastly, can you take out the Release notes from your README.md file ? It detracts from the actual instructions of how to get started and about what this module is doing. It seems that it would be better served being put in a separate release notes file as well as in the release notes of the module in general.

**Comment by pfn** [comment]
`1.3.18`? that's not the least bit current.

as for your latter error, like all shell commands that have sub-commands, you must quote the entire command you want to run.

`sbt "gen-android ...."`

As for documentation, the readme is the readme, you must read the readme in its entirety. If you would like to contribute better documentation that sits independently of the readme, please submit a PR.

**Comment by accesio** [comment]
Sorry about the 1.3.8 
The example I pasted was from another stackoverflow pastebuffer that I hadn't cleared.

I'm using 
```
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.4.8")
```

I think it could be more useful to include that instruction in your README.md about quoting entire commands and include an example:
```
sbt "gen-android  android-19 com.FooBar FooBar"
```

I'm used to the android command line tools where you just write as is without worry about quoting. IE.
```
android create project -g -v 1.3.1  --target 19 --path $PATH --package com.Foo --activity MainActivity
```

Please note, my issue is that release notes might possibly be better served as GitHub release notes 
( https://github.com/blog/1547-release-your-software ) and after that it would be easier to glean how to get up and running faster when reading the README.md
