### ISSUE TITLE
Error running gen-android-sbt after Android command line w/gradle setup

### ISSUE THREAD

**Issue by accesio** [pfn/android-sdk-plugin#196]
Hi ,

I see an error when using the 1.4.8  version of the android-sdk-plugin when I use it on a project created with gradle support, but I don't see the error if I create the project without gradle support.

The error I see is Call requires API level 3(current min is 1)   (See below )

To recreate the error I do the following:

```bash
android create project -g -v 1.3.1  --target 14 --path LawBlog --package com.LawBlog --activity MainActivity
cd LawBlog
sbt "gen-android-sbt"
sbt compile
```

Produces the error 
[error] [NewApi] target/android-bin/classes/com/LawBlog/MainActivityTest.class:Call requires API level 3 (current min is 1): new android.test.ActivityInstrumentationTestCase2
[error] [NewApi] target/android-bin/classes/com/LawBlog/MainActivityTest.class:Class requires API level 3 (current min is 1): android.test.ActivityInstrumentationTestCase2

Note that no error occurs for the following ( sans -g -v 1.3.1 ) 

```bash
android create project  --target 14 --path LawBlog --package com.LawBlog --activity MainActivity
cd LawBlog
sbt "gen-android-sbt"
sbt compile
```

**Comment by pfn** [comment]
`echo 'minSdkVersion in Android := "4"' >> build.sbt`

**Comment by pfn** [comment]
Or set it appropriately in AndroidManifest.xml
