### ISSUE TITLE
Aar projects not generating R class in 1.4.10

### ISSUE THREAD

**Issue by Taig** [pfn/android-sdk-plugin#198]
The problem came up with 1.4.10, the same code works with 1.4.9

Sample project: https://github.com/taig/aar-issue

**Comment by pfn** [comment]
Using `android.AutoBuild` in conjunction with `androidBuildAar` is a misconfiguration. Replace `android.AutoBuild` with `sbt.Build`.

The `sourceGenerators` setting in that build file is a workaround for the misconfiguration above. Remove it.

**Comment by Taig** [comment]
Thank you (:
