### ISSUE TITLE
proguard rules from aar dependencies are not included

### ISSUE THREAD

**Issue by oxc** [pfn/android-sdk-plugin#199]
aar dependencies can optionally include a progard.txt file containing the (additional) proguard rules required for this dependency.

They should be taken into account when generating the full ruleset in the [proguardConfigTaskDef](https://github.com/pfn/android-sdk-plugin/blob/master/src/tasks.scala#L865)

**Comment by pfn** [comment]
workaround for now:
```scala
proguardConfig in Android <++= Def.task { (aars in Android).value flatMap { a =>
    val pg = a / "proguard.txt"
    if (pg.isFile) IO.readLines(pg) else Seq.empty
}
```
