### ISSUE TITLE
Allow specification of max heap size for dex

### ISSUE THREAD

**Issue by emptyflash** [pfn/android-sdk-plugin#206]
I frequently hit an issue where I get an OutOfMemoryError while dexing
```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
... stacktrace ...
```

I thought this might be because I didn't have multidex enabled (which I really needed anyway, I have a lot of dependencies), but I'm still getting the error. According to some of the [StackOverflows](http://stackoverflow.com/questions/25013638/android-studio-google-jar-causing-gc-overhead-limit-exceeded-error/25013822#25013822) I've read the way to fix this is to specify the `javaMaxHeapSize` in their Build.gradle file.

The only way I've found to fix it for me is to run `sbt clean` and then rerun my build. It really seems to only happen on a proguard cache hit.

It might be useful to allow users to specify the max heap size for dex in their sbt build.

**Comment by pfn** [comment]
`dexMaxHeap in Android`
