### ISSUE TITLE
Proguard step does not resolve sources for multiproject builds where subproject is android

### ISSUE THREAD

**Issue by zainab-ali** [pfn/android-sdk-plugin#207]
See [here](https://github.com/zainab-ali/multiproject-with-android-subproject/tree/master/app).

Running `sbt app/android:run` to go through the `proguard` step generates the following output `Warning: com.alizai.example.MainActivity: can't find referenced class com.alizai.example.HelloWorld$`.

The sources are not being resolved correctly and calling the missing classes resolves in a `NoClassDef` error. 

At the moment we are using a hackaround where we publish to the local ivy repo and pull it down in the subproject which is not ideal.

**Comment by pfn** [comment]
where's your build.sbt

if app doesn't dependsOn(root) and/or exportJars is not set, then this is not a bug

**Comment by zainab-ali** [comment]
Oops, didn't commit the `build.sbt` by mistake. Changing  the affected projects to have the setting `exportJars := true` and adding them as jars rather than using the class file directory worked, thanks!
