### ISSUE TITLE
Android build tools > 22 fail when calling dexMainClasses script

### ISSUE THREAD

**Issue by veegee** [pfn/android-sdk-plugin#208]
I have to force this:
`buildToolsVersion in Android := Some("22.0.1") // later major versions seem to fail for dexMainClasses script`
because using a newer version causes the dex main classes list generation to fail. Newer build tools versions seem to not allow you to call the `mainDexClasses` script.

**Comment by pfn** [comment]
Specify dexMainClasses explicitly.

**Comment by pfn** [comment]
For that matter, what is the error.

**Comment by veegee** [comment]
The whole point is to have it generate that for you. I don't know what the main classes should be, so I want the build tools to generate it for me.

The error is that the `mainDexClasses` script in newer build tools versions returns this message when invoked:

```
Usage:
Short version: Don't use this.

Slightly longer version: This tool is used by mainDexClasses script to build
the main dex list.
```

Older build tools versions invoke the script successfully.

**Comment by pfn** [comment]
I don't see this error in 23.0.1

**Comment by pfn** [comment]
rather, this message gets printed out, but maindexlist.txt is still created.

**Comment by veegee** [comment]
It's created, but it's empty.

**Comment by pfn** [comment]
that explains why the test passes  ;-)

**Comment by pfn** [comment]
I'm guessing you're on Windows? Looks like mainDexClasses.bat has a bug on windows, it passes "" for --disable-annotation-resolution-workaround when nothing should be passed at all

**Comment by veegee** [comment]
Yes, I'm on Windows 8.1. Sorry, should have mentioned that in the bug report.

**Comment by pfn** [comment]
https://code.google.com/p/android/issues/detail?id=187721

**Comment by pfn** [comment]
see workaround I documented in the above issue
