### ISSUE TITLE
NoSuchMethodError with SBT 0.13.9

### ISSUE THREAD

**Issue by Thiross** [pfn/android-sdk-plugin#217]
[info] Set current project to tutuur (in build file:/D:/gitroot/tutuur/)java.lang.NoSuchMethodError: sbt.ConfigurationReport.details()Lscala/collection/Seq;
        at android.Tasks$$anonfun$19$$anonfun$apply$23.apply(tasks.scala:293)
        at android.Tasks$$anonfun$19$$anonfun$apply$23.apply(tasks.scala:293)

...

[error] (android:checkAars) java.lang.NoSuchMethodError: sbt.ConfigurationReport.details()Lscala/collection/Seq;
[error] Total time: 0 s, completed 2015-10-23 15:53:31

**Comment by pfn** [comment]
Sounds like you're not on 0.13.9, check build.properties

--

**Comment by pfn** [comment]
Verify by running `sbtVersion` in your project.

**Comment by pfn** [comment]
unless reproduced otherwise, this does not occur in 0.13.9, your build.properties is specifying an older version of sbt
