### ISSUE TITLE
TypedLayoutInflater performs illegal cast

### ISSUE THREAD

**Issue by Taig** [pfn/android-sdk-plugin#221]
The `inflate` method of `TypedLayoutInflater` does not respect the varying return value behavior of the underlying `Inflater.inflate` method.

````scala
implicit class TypedLayoutInflater(val l: LayoutInflater) extends AnyVal {
  def inflate[A](tl: TypedLayout[A], c: ViewGroup, b: Boolean) =
    l.inflate(tl.id, c, b).asInstanceOf[A] // Returns c if b == true
  def inflate[A](tl: TypedLayout[A], c: ViewGroup) =
    l.inflate(tl.id, c).asInstanceOf[A] // Returns c
  def inflate[A](tl: TypedLayout[A]) = l.inflate(tl.id, null).asInstanceOf[A]
}
````

[Android documentation](http://developer.android.com/reference/android/view/LayoutInflater.html#inflate(int, android.view.ViewGroup, boolean))

I find the underlying behavior of the `LayoutInflater` very confusing. I've never been in the situation where I wanted the root view after inflating. Instead I find myself working around this behavior all of the times. Especially for the purpose of typed layout inflating it might therefore make sense to not support the default behavior and instead always return the inflated view (in this fashion):

````scala
def inflate[A](tl: TypedLayout[A], c: ViewGroup, b: Boolean) = {
    val view = l.inflate(tl.id, c, b)
    val child = if(b) {
        view.getChildAt(view.getChildCount - 1)
    } else {
        view
    }
    view.asInstanceOf[A]
}
````

**Comment by pfn** [comment]
please submit a PR
