### ISSUE TITLE
Resources styles.xml error loading 

### ISSUE THREAD

**Issue by Ewg777** [pfn/android-sdk-plugin#227]
When I try to build my project using Idea facing this error: 
![Image of Yaktocat](https://habrastorage.org/files/7e8/208/034/7e82080344f743c791ef25158ffb7f17.png)

What's the problem with?

This resources declared at com.android.support/appcompat-v7

**Comment by pfn** [comment]
What error? Your image has no error.

**Comment by Ewg777** [comment]
@pfn seems appcompat doesn't attached to the project 
![Image of Yaktocat](https://habrastorage.org/files/456/f93/73e/456f9373ee9d4d54902191b2eaa69ac5.png)
![Image of Yaktocat](https://habrastorage.org/files/45f/3f5/c0f/45f3f5c0f1384ffab94443dc4fdf4120.png)

**Comment by pfn** [comment]
This is an IDEA problem. Any builds should always be done through sbt.
