### ISSUE TITLE
Migrating from Android Scala Plugin 1.5.8 to 1.5.9

### ISSUE THREAD

**Issue by pamu** [pfn/android-sdk-plugin#229]
Migrating from Android Scala Plugin 1.5.8 to 1.5.9 producing compilation errors 

object Keys is not a member of package android
object PromptPasswordsSigningConfig is not a member of package android
object Plugin is not a member of package android

**Comment by pfn** [comment]
Your download got corrupted, remove the downloaded plugin from your ivy
cache and try again.

--

**Comment by pfn** [comment]
Closing due to lack of further information (and hundreds of downloads without this issue).
