### ISSUE TITLE
android/res not being included

### ISSUE THREAD

**Issue by darkfrog26** [pfn/android-sdk-plugin#231]
I recently updated to the latest version of this plugin and now it's not picking up the files in android/res/values/*.xml.

I do have a multi-project build and everything was working fine, but now when I try to compile the android module I get this:

```
Error: No resource found that matches the given name (at 'theme' with value '@style/GdxTheme')
```

`GdxTheme` is defined in android/res/values/styles.xml:

```xml
<resources>

    <style name="GdxTheme" parent="android:Theme">
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:colorBackgroundCacheHint">@null</item>
        <item name="android:windowAnimationStyle">@android:style/Animation</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowFullscreen">true</item>
    </style>

</resources>
```

**Comment by pfn** [comment]
Need much more specifics.

**Comment by darkfrog26** [comment]
@pfn, I'm not sure what else to say. I was hoping there had been a change in the way the `res` path is loaded and a setting I need to set or change.  My project is originally based off of this project:

https://github.com/ajhager/libgdx-sbt-project.g8

However, it has been updated to use android-sdk-plugin 1.5.9.

**Comment by pfn** [comment]
please provide a minimal test case that reproduces this issue

**Comment by darkfrog26** [comment]
Can you perhaps explain what aspect of the plugin defines where to pick up the `res` folder?

**Comment by pfn** [comment]
ProjectLayout

**Comment by darkfrog26** [comment]
Is there any way I can get it to dump the path to `res`?

**Comment by darkfrog26** [comment]
I fear it may be looking in `root/res` instead of `root/android/res`

**Comment by pfn** [comment]
android:projectLayout, show android:extraResDirectories

**Comment by darkfrog26** [comment]
```
> android:projectLayout
[info] Ant(/home/mhicks/projects/clients/myproject/myproject-mobile/android)
> show android:extraResDirectories
[info] List()
```

**Comment by pfn** [comment]
Then it will pick up from android/res

**Comment by pfn** [comment]
last android:collectResources

**Comment by pfn** [comment]
and ask gitter/irc first

**Comment by darkfrog26** [comment]
Sorry, I'll ask in IRC. Thanks.
