### ISSUE TITLE
Remove `classDirectory` from `unmanagedClasspath`

### ISSUE THREAD

**Issue by dancingrobot84** [pfn/android-sdk-plugin#236]
Hi Perry,

I've noticed that [this commit](https://github.com/pfn/android-sdk-plugin/commit/16146db192b2302369cc54289195fe9bb19119ca) adds `classDirectory` into `unmanagedClasspath` to fix some things for sbt-idea. Unfortunately, it causes errors when building Android project in IDEA. It happens because `classDirectory` appears twice when building: one time because it is set as output directory for compiler, next time because it is added as a library dependency to module. Its duplicate appearance causes Proguard to raise "Duplicate entry" errors, thus crashing the whole build.

While I can introduce a workaround into sbt-structure, I think that this issue should be fixed in android-sdk-plugin since this change was introduced solely for sbt-idea plugin, which is obsolete now and does not support nor IDEA 14/15, neither latest versions of android-sdk-plugin.

WDYT?

**Comment by pfn** [comment]
Yeah, sounds good, I'll remove the legacy cruft, thanks for pointing it out.
