### ISSUE TITLE
Upgrade from 1.4.7 -> 1.5.11

### ISSUE THREAD

**Issue by spidfire** [pfn/android-sdk-plugin#239]
This piece of code doesn't work for me anymore after i update to 1.5.11

```
localProjects in Android <+= baseDirectory {
  b => AutoLibraryProject(b / "cardview")
}
```

```
\build.sbt:36: error: diverging implicit expansion for type android.ProjectLayout => android.BuildOutput                                                                                                                                          
starting with method LayoutOutputExtension in object BuildOutput                                                                            
  b => AutoLibraryProject(b / "cardview")                                                                                                   
                         ^               
```
Any advice on fixing this?

**Comment by pfn** [comment]
Typically, if one wishes to use AutoLibraryProject, one should define them in `project.properties` with something like `android.library.reference.1=cardview` for this case.

If you want to do it from sbt, it can be set as `localProjects += AndroidLibraryProject(baseDirectory.value / "cardview")(outputLayout.value)`

Normally, it is not desired to configure AutoLibraryProject from sbt (usually one would want to use a full multi-project setup with `androidBuildWith`, etc)
