### ISSUE TITLE
Cannot depend on MutableSetting in task

### ISSUE THREAD

**Issue by joprice** [pfn/android-sdk-plugin#242]
Modifying a mutable setting doesn't trigger sbt to update dependencies on the setting, since the build State has not been modified. It would be convenient to be able to configure other settings based on whether it is a debug build or not. For instance, with a normal setting, I would expect this to change when setDebug/setRelease are called:

```scala
libraryDependencies ++= Seq({
  val suffix = if ((apkbuildDebug in Android).value()) "" else  "-no-op"
  "com.squareup.leakcanary" % s"leakcanary-android$suffix" % "1.3.1"
})
```

However, those commands simply modify the setting, without trigger libraryDependencies to be re-evaluated. Instead, you have to modify the new setting itself:

```scala
set apkbuildDebug in Android := MutableSetting(true)
```

Is there a reason to not implement `setDebug` as a command that modifies the session?

**Comment by pfn** [comment]
`apkbuildDebug` is solely used to determine whether the build type is debug or release from within a task. It must not be used to configure any settings. 

Instead, use any of `flavors`, `buildTypes` and flavor projects to accomplish what you want.

Forcing evaluation of session settings (the `set` command)  breaks build types and flavors (the `variant` command)
