### ISSUE TITLE
versionCode increment option for release builds

### ISSUE THREAD

**Issue by aafa** [pfn/android-sdk-plugin#243]
In my projects I'm using a custom task for build number increment on final release stage where number is stored within a plain file. 

Will that be a good thing to have within plugin as an optional setting\task?

**Comment by Taig** [comment]
Are you talking about the `versionCode`? I tend to simply use a timestamp or more human-readable datetime representation. That's easy to implement and gives you the additional information of when the APK was built.

**Comment by aafa** [comment]
Thats a good point. In my case however I'm using this key for storing actual build number to show full version like this x.x.x(xx) in both GP and app About page.

**Comment by pfn** [comment]
I would generally avoid wanting this in the plugin as it's easily done in an outside task. Things like `sbt-release` or calculating version numbers using git. I often use `git rev-list --commit-count master` as version code

**Comment by aafa** [comment]
Ok, solid thoughts.
