### ISSUE TITLE
Cannot import a project that uses android-sdk-plugin

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [pfn/android-sdk-plugin#248]
Even though I have set in my `build.sbt` the `sdkPath` variable:

    sdkPath in Global := "/home/user/bin/android-sdk"

and set the variable ANDROID_HOME in `.bashrc`, I cannot import the project in IDEA.

    [error] set the env variable ANDROID_HOME pointing to your Android SDK

Related bug that I have opened in IDEA:
https://youtrack.jetbrains.com/issue/SCL-9836

But I can launch sbt from the command line and it works.

**Comment by pfn** [comment]
remove in Global

**Comment by DavidPerezIngeniero** [comment]
I've tried also:

    sdkPath in android := "....."

**Comment by pfn** [comment]
You must also launch the ide after setting the variable. If you launch from
a desktop environment, then you must log in again, and as far as I know, a
desktop environment does not read bashrc.

**Comment by DavidPerezIngeniero** [comment]
I've tried also to launch from the command line, where I know the value of each environment variable.

**Comment by pfn** [comment]
Not an issue, use gitter for chatty support

**Comment by DavidPerezIngeniero** [comment]
OK

**Comment by DavidPerezIngeniero** [comment]
Cause of the problem was I mispelled the value of ANDROID_HOME in the `idea.sh` script, and I didn't remember about it.
