### ISSUE TITLE
Proguard-sbt.txt file and the Intellij refresh buttton

### ISSUE THREAD

**Issue by AbimbolaE** [pfn/android-sdk-plugin#249]
Hi pfn,

I'm loving the android-sdk-plugin after I finally wrapped my head around some of the Proguard config rules. However, I still haven't figured out which task generates the `proguard-sbt.txt` file which is generated in the root project directory. Currently, I am using Intellij's refresh button to regenerate it but this is not the most optimal way to work in my opinion.

How exactly can I regenerate that file using SBT from the command line?

**Comment by pfn** [comment]
This file is generated by intellij and unused by sbt (and for that matter, unused at all, except when trying to build with intellij)
