### ISSUE TITLE
JSON libraries and Proguard

### ISSUE THREAD

**Issue by AbimbolaE** [pfn/android-sdk-plugin#250]
Hi there,

I'm currently looking for a Scala JSON library which can parse case classes into JSON strings and Vice versa. I've tried using json4s but I think that Proguard is deleting the class metadata which json4s would normally use to infer the fields and a produce a JSON string. I tried json4s on a plain SBT project with no proguard and it worked beautifully with no hassle whatsoever (`NoTypeHints` was my specified format). I tried it again within an Android project but it output was `{}`.

Anyone have any example of the JSON library they use along with the Proguard settings they enable to parse case classes to and from json?

**Comment by Taig** [comment]
I've been successfully using play-json 2.3.x with the proguard rules below (not sure if any of them have to do with play-json or its dependencies):

```
-keepattributes EnclosingMethod,InnerClasses,Signature
-keepattributes *Annotation*
-keepclassmembers class ** { @com.squareup.otto.Subscribe public *; @com.squareup.otto.Produce public *; }
-dontwarn okio.Okio
-dontwarn okio.DeflaterSink
-dontwarn org.joda.convert.JDKStringConverter$9
-dontwarn scala.xml.parsing.MarkupParser
-dontwarn com.caverock.androidsvg.SVGImageView
-dontwarn resource.jta.**
-dontwarn org.threeten.bp.chrono.JapaneseEra
-dontwarn com.fasterxml.jackson.databind.ext.DOMSerializer
-dontwarn com.google.android.gms.**
```

For new projects I prefer circe which does also work fine.

You should probably be asking this kind of stuff at the gitter channel rather than creating an issue. pfn is very helpful and does usually respond in no time.

**Comment by pfn** [comment]
+1, use the appropriate forums, gitter, mailing list, etc. Thanks

**Comment by AbimbolaE** [comment]
@pfn Sorry about that! Can I get a link to the forum / mailing list? I honestly am not sure where to find them...

**Comment by pfn** [comment]
https://groups.google.com/forum/m/#!forum/scala-on-android

And there is a gitter link at the top of the readme
