### ISSUE TITLE
A possible replacement for ProGuard

### ISSUE THREAD

**Issue by stanch** [pfn/android-sdk-plugin#68]
Hi,

At *ScalaDays* I was made aware that Sébastien Doeraene (@sjrd) and the *Scala.JS* team had developed their own tool for stripping out classes and methods. It is 1-2 orders of magnitude faster then *ProGuard*, because it emits information straight from the compiler, and is incremental. Unfortunately, it’s currently limited to the *Scala.JS* compiler, and will require some work to be adapted. But I feel that it could be a tremendous benefit for the Scala-on-Android community.

Below is the outline provided by Sébastien himself:
> So the actual work is done in ScalaJSOptimizer under:
https://github.com/scala-js/scala-js/tree/master/tools/src/main/scala/scala/scalajs/tools/optimizer
It relies on the analysis performed in Analyzer, then it strips useless things in ScalaJSOptimizer (or rather, emits only the necessary parts in a new place).

> This tool reads information stored in .sjsir files, which are the IR files of Scala.js. They are created by the Scala.js compiler plugin in
https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/scala/scalajs/compiler/GenJSFiles.scala#L26
based on information collected in
https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/scala/scalajs/compiler/ClassInfos.scala
by
https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/scala/scalajs/compiler/GenJSCode.scala
However, it is likely that you can find the same information directly from .class files.

> The really important thing for speed is in the optimizer. From the .sjsir files, it reads the following condensed information:
https://github.com/scala-js/scala-js/blob/master/ir/src/main/scala/scala/scalajs/ir/Infos.scala
This is the stuff it really cares about, and that you should construct differently from .class files. The important thing is to keep these information in memory between two runs, in a cache that invalidates the data only if the underlying .class file has changed. In Scala.js we do that here:
https://github.com/scala-js/scala-js/blob/master/tools/src/main/scala/scala/scalajs/tools/optimizer/ScalaJSOptimizer.scala#L289
Now, the analyzer can run from scratch on these data every time, because that step is fast. You can probably reuse the Analyzer almost as is:
https://github.com/scala-js/scala-js/blob/master/tools/src/main/scala/scala/scalajs/tools/optimizer/Analyzer.scala
Then comes the emission of what's needed. Again, this has to be "incremental" in the sense that it has to avoid re-emitting the purged .class files if 1) their original .class file has not changed and 2) the parts within that the analyzer selected has stayed the same. In Scala.js we keep that in memory as well, but in your case you can probably cache the resulting .class files on disk, or any other format that is best to hand over to DES.
Subsequently, DES should be reapplied only to the purged .class files that have changed since last time.

> That's basically the idea. Feel free to ask any details.

**Comment by jimfulton** [comment]
An advantage of this approach over a faster Proguard is that it would allow creation of library projects that are, presumably, much easier to consume from Java-based android projects.

**Comment by pfn** [comment]
This is really out of the scope for this plugin.

If someone wants to write scala.dx, yay (and I've thought about it, but no, maybe scala 2.12/3.x+ will force hands), but yeah, otherwise far out of scope.

**Comment by pfn** [comment]
Also, this wouldn't enable making scala libraries easier to consume from java projects, you'd still have to go through the pre-dexed libraries setup, and compile against the original jar, etc. It's *painful*.

The best approach if you want to use scala libraries from java projects: let the build pull in scala-library transitively, enable proguard, add scala rules in your aar's proguard.txt
