### ISSUE TITLE
Facebook’s ProGuard?

### ISSUE THREAD

**Issue by stanch** [pfn/android-sdk-plugin#83]
I’ve quickly tried replacing the *ProGuard* from `build.sbt` with the `jar` from https://github.com/facebook/proguard, and indeed it seems to give a speedup. What do you think? Also see https://groups.google.com/forum/#!topic/scala-on-android/V_SREZrGU2Y.

**Comment by pfn** [comment]
It looks like facebook's fork is dead as it's still on 4.x while we've moved on with proguard 5.x, if facebook ever updates their fork and publishes it to central, I may make a flag that allows toggling it via libraryDependencies.
