### ISSUE TITLE
using AutoBuild with androidBuild* results in duplicated sourcegenerators (and other things)

### ISSUE THREAD

**Issue by pfn** [pfn/android-sdk-plugin#88]
for now, workaround by doing

`sourceGenerators in Compile <<= (sourceGenerators in Compile) (g => Seq(g.last))`

other things get multiply added, but are less of an issue, including:
`unmanagedClasspath`
`managedClasspath`
`resolvers` (for android sdk local repos)
`cleanFiles`

**Comment by DavidPerezIngeniero** [comment]
The same with 0.13.x syntax:
```scala
    sourceGenerators in Compile :=Seq((sourceGenerators in Compile).value.last),
```

**Comment by pfn** [comment]
1.4.10 changes sourceGenerators so that it properly uses each individual task. This workaround no longer applies. The proper fix is to remove the conjunction of `android.AutoBuild` and individual `androidBuildXXX` mechanisms.

**Comment by pfn** [comment]
AutoBuild is deprecated, not really an issue anymore
